apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../../manifests
patches:
- path: deployment.yaml
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/type=app
