apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../manifests/catalog
resources:
- statefulset-mysql.yaml
- service-mysql.yaml
patches:
- path: deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: catalog
    namespace: catalog
