apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - efsstorageclass.yaml

configMapGenerator:
- name: assets-efsid
  namespace: assets
  envs: [config.properties]
  
vars:
- name: EFS_ID
  objref:
    kind: ConfigMap
    name: assets-efsid
    apiVersion: v1
  fieldref:
    fieldpath: data.EFS_ID
configurations:
  - env-var-transformer.yaml
