kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otel-ci-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-ci-role
subjects:
  - kind: ServiceAccount
    name: adot-collector-ci
    namespace: other
