apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: other
configMapGenerator:
- name: adot-ci-env
  env: config.properties
vars:
- name: ADOT_IAM_ROLE_CI
  objref:
    kind: ConfigMap
    name: adot-ci-env
    apiVersion: v1
  fieldref:
    fieldpath: data.ADOT_IAM_ROLE_CI
- name: EKS_CLUSTER_NAME
  objref:
    kind: ConfigMap
    name: adot-ci-env
    apiVersion: v1
  fieldref:
    fieldpath: data.EKS_CLUSTER_NAME
configurations:
- configuration.yaml
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- opentelemetrycollector.yaml
